version: 2.1

executors:
  gcp-executor:
    docker:
      - image: cimg/google-cloud:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: gcp-executor
    steps:
      - checkout

  build_docker_image:
    executor: gcp-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Authenticate with Google Cloud
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - run:
          name: Build and Push Image
          command: |
              docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest .
              docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest

  deploy_to_gke:
    executor: gcp-executor
    steps:
      - checkout
      - run:
          name: Authenticate and Deploy
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud config set project $GOOGLE_PROJECT_ID
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION
              kubectl apply -f kubernetes-deployment.yaml

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image